drop table estaEnCarrito;
drop table carritos;
drop table usuarios;
drop table clientesSucursales;
drop table cantProductosComprados;
drop table compras;
drop table clientes;
drop table stockDisponible;
drop table enDisplay;
drop table estantes;
drop table bodegas;
drop table pedidos;
drop table acuerdosCompra;
drop table proveedores;
drop table promociones;
drop table productos;
drop table sucursales;
commit;